
services:
  postgres:
    image: postgres:15-alpine
    container_name: study-tracker-db
    environment:
      POSTGRES_DB: study-tracker-0db
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
