CREATE TABLE tb_topic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    color VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_topic_user
        FOREIGN KEY (user_id)
        REFERENCES tb_user(id)
);