CREATE TABLE tb_study_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    studied_at TIMESTAMP,
    status VARCHAR(255) NOT NULL,
    topic_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_study_session_topic
        FOREIGN KEY (topic_id)
        REFERENCES tb_topic(id),

    CONSTRAINT fk_study_session_user
        FOREIGN KEY (user_id)
        REFERENCES tb_user(id)
);